### ISSUE TITLE
Filename conversion problem

### ISSUE THREAD

**Issue by chambm** [brodieG/diffobj#101]
Try this command:
`diffobj::diffPrint(paste(rep("A", 500000), collapse=""), rep("B", 50000))`

I get:
`Error in file.info(x, extra_cols = FALSE) : 
  file name conversion problem -- name too long?`

I found this bug when trying to diff two very long strings (actually files read into long strings).

**Comment by brodieG** [comment]
Thanks for reporting with a good minimal reproducible example.  In my system this actually segfaults, so clearly there is something quite wrong here.  Obviously I did not test for very very long lines.  Until I fix this, you can `strsplit` your input by `""` so that there is one character per line.

Even with that, please keep in mind that inputs that are 500K long and have many differences are likely to tax the system.  You may want to try `ses` first which just returns the shortest edit script without  any of the fancy display stuff, but even that will struggle if you have more than 20K **differences** between your strings.

If you can publicly post the actual inputs that you are trying to diff that would be useful for testing for me, although not necessary to resolve this particular issue.

DEVNOTES:
```
> diffobj::diffPrint(paste(rep("A", 5e3), collapse=""), rep("B", 5e2))   # works
> diffobj::diffPrint(paste(rep("A", 5e4), collapse=""), rep("B", 5e2))
Error: segfault from C stack overflow
> diffobj::diffPrint(paste(rep("A", 5e4), collapse=""), rep("B", 5e2), rds=FALSE)
Error: segfault from C stack overflow
```

**Comment by chambm** [comment]
My strings do have newlines, but in memory they are represented with one character vector. When I use readLines, my diff shows `\t` in my strings instead of printing tabs.

**Comment by brodieG** [comment]
That's weird.  If your strings have newlines they should be read as vectors with as many elements as there are newlines by `readLines`.  Is it possible newlines and tabs are escaped in your text files (i.e. if you look at the raw text you'll see stuff like 'hello\\nthere\\ttoday')?

**Comment by chambm** [comment]
No I only see "hello\nthere\ttoday". And when I `cat` it, it renders the newlines and tabs properly.

**Comment by brodieG** [comment]
Then I really don't understand what's going on.  `readLines` should be splitting your strings by the newlines.  Consider:
```
tmpf <- tempfile()
cat("hello\nthere\n", file=tmpf)
readLines(tmpf)
#  [1] "hello" "there"
```
If you can post a snippet of the file the reproduces the problem (i.e. no splitting by newlines) then I can look at it further.  Otherwise I'm pretty stumped.

**NOTE**, `diffPrint` always diffs the output of `print`/`show`, so you will always see tabs and newlines there.  If you want to `diff` the actual character values then use `diffChr`.  Compare these two:
```
diffChr('a\nb\tc', 'a\nB\tc')
diffPrint('a\nb\tc', 'a\nB\tc')
```
This does not address why `readLines` is not breaking up your strings by the newlines though.

**Comment by chambm** [comment]
Using `read.delim` instead of `readLines` or `readr::read_file` produced much better output. I guess this was just confusing to me because I think of a line-by-line diff as primarily working on a string (or vector of strings) rather than a structured object (like a data.frame).

**Comment by brodieG** [comment]
Looks like we cross posted.  Let me know if you continue to have issues.  And yes, this is a bit confusing because `diffPrint` works on the **text** representation of objects as we are used to seeing them on the R command line.  `diffChr` does the diff on the raw text.

**Comment by chambm** [comment]
`readLines` does split up by line, but doesn't interpret the tabs. It was `readr::read_file` that doesn't split up by newlines.
```
tmpf <- tempfile()
cat("hello\tthere\nworld\tfair\n", file=tmpf)
readLines(tmpf)
```

**Comment by brodieG** [comment]
The specific issue you ran into should be fixed with:
```
devtools::install_github('brodieg/diffobj@development')
```
**However**, there is a bug in `grep` that has nothing to do with `diffobj` that is illustrated by the following causing a stack overflow:
```
reg <- "(A|B)*" 
string <- paste0(rep("A", 5e4), collapse="")
grep(reg, string, perl=TRUE)
```
so even if you get past the issue that you first reported you will very likely run into the `grep` bug.  That said, it seems that the need for handling 50K+ wide character elements is no longer here now that you're reading your files with `readLines`, so I think you'll be okay.

Unless I hear otherwise from you I consider this issue closed, though the issue won't formally be closed until this branch is merged into master.
