### ISSUE TITLE
Suppress target print out

### ISSUE THREAD

**Issue by coatless** [brodieG/diffobj#112]
I'm looking for the ability to _suppress_ the "target" printout

Consider the following:

```r
library(diffobj)

student = function() { 
  toad = 1
  return(toad)
}

solution = function() {
  toad = 2
  return(toad)
}

diffPrint(target=solution, current=student)
```

This gives:

![target and current](https://user-images.githubusercontent.com/833642/33580160-b972794a-d911-11e7-9aa8-7a694bf3fb02.png)

I would like to only show and provide the output of:

![Student solution](https://user-images.githubusercontent.com/833642/33580212-e521cb22-d911-11e7-8a08-99a82b787190.png)

**Comment by brodieG** [comment]
Is an HTML only output solution acceptable?  Might be super easy to do with css.  Or would you worry that your students could mess with css (e.g. css inspector)?

**Comment by coatless** [comment]
I'm confident that they would be able to figure out if I added a local CSS hack, e.g. `display: none`.

**Comment by brodieG** [comment]
Ok, assuming you are using HTML output the following works for me.  I'm not sure how robust it is as I don't remember if there are any odd interdependencies in the HTML/JS, but hopefully it will do for your purposes:

```
library(diffobj)

style <- StyleHtmlLightYb()                    # explicitly generate style object to modify
style@funs@line.delete <- function(x) ""    # suppress instead of format
style@funs@banner.delete <- function(x) ""  # suppress instead of format

diffPrint(target=solution, current=student, style=style, mode='unified')
```

See `?Style` for details.


<img width="175" alt="screen shot 2017-12-04 at 6 55 27 pm" src="https://user-images.githubusercontent.com/6105908/33582767-d8f4bbf8-d924-11e7-9bcc-af5727c7094c.png">

Since this is a pretty specific use case I am not planning on adding a friendlier interface for it.  If this works for you please close the issue.  If you need additional guidance or it seems like this is not workable, let me know.

**Comment by coatless** [comment]
@brodieG excellent. Thanks!
