### ISSUE TITLE
Maybe any should return TRUE

### ISSUE THREAD

**Issue by zx8754** [brodieG/diffobj#75]
Maybe my logic is failing me, but to have it consistent with `all.equal()`, is it not better to return *TRUE* if there are **no** differences?

From the manual:
> any returns TRUE if there are differences 

Relevant SO post - http://stackoverflow.com/questions/39538431

**Comment by brodieG** [comment]
After 74 self reported issues, I finally have a real one!  This is probably the most excited I'll ever be in my life to get a reported issue...

To actually address your question, the `diff*` methods are designed to identify differences, so from that perspective when using `any`, I think of the question being asked as "are there any differences (and if so, what are they)", as opposed to "are there no differences".  In other words, `any(diff*)` is really much closer to a hypothetical `any.different` than `all.equal` function.  I think the possible alternative interpretation would be that `any(diff*)` could correspond to `any.equal()`, but I don't think that is very useful.  Just the fact that we are talking about the `any` method makes the whole thing somewhat incompatible with `all.equal`.

A good comparison is what happens when you run `git diff` on a file with no changes, which is you get nothing at all.

Let me know if you still feel that `any(diff*)` should return TRUE if there are no differences.

**Comment by zx8754** [comment]
Yes, comparing to `git diff` makes more sense.
