### ISSUE TITLE
Warnings When Comparing Large data.tables

### ISSUE THREAD

**Issue by brodieG** [brodieG/diffobj#96]
This one came up when comparing two data.tables where one had one more column than the other:
```
Warning messages:
1: In cbind(integer(2L), abs(apply(seq.dat, 1L, diff))) :
  number of rows of result is not a multiple of vector length (arg 1)
2: In cbind(integer(2L), abs(apply(seq.dat, 1L, diff))) :
  number of rows of result is not a multiple of vector length (arg 1)
```

**Comment by chambm** [comment]
:+1 I saw that one too and wasn't sure whether it was coming from testthat or diffobj. I'm trying to find a good diff solution that will comprehensibly say "these two files are different because one has an extra column". Line by line diff is not well suited to this but testthat's default error messages are even worse.

**Comment by brodieG** [comment]
Not a great workaround, but if you are specifically looking for added/removed columns doing an `as.list(DT)` can produce slightly more useful output.
